# Generated by Django 6.0.1 on 2026-01-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_client_address_client_company_name_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allow_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='allow_voice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='allow_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='forced_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_keys', to='relay.twilioaccount'),
        ),
    ]
