# Generated by Django 6.0.1 on 2026-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0003_apikey_allow_sms_apikey_allow_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccount',
            name='capability_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='capability_voice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='capability_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
