# Generated by Django 6.0.1 on 2026-01-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0004_twilioaccount_capability_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccount',
            name='name',
            field=models.CharField(blank=True, help_text='Friendly name for identification', max_length=255),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary Twilio phone number for this account', max_length=20),
        ),
    ]
