# Generated by Django 6.0.1 on 2026-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0005_twilioaccount_name_twilioaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioaccount',
            name='sid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
