# Generated by Django 6.0.1 on 2026-01-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0006_alter_twilioaccount_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Voice Call')], max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField(blank=True)),
                ('twilio_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relay.twilioaccount')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relay.apikey')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='relay.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
