# Generated by Django 6.0.1 on 2026-01-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0007_auditlog_communicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='pattern',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='twilioaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='twilioaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
