# Generated by Django 6.0.1 on 2026-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0008_alter_routingrule_pattern_alter_routingrule_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='from_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='to_number',
            field=models.CharField(max_length=50),
        ),
    ]
